---
galaxy_info:
  author: Matthew Finlayson
  description: Installs and configures thumbor with aws backing
  company: Jive Software
  platforms:
    - name: Ubuntu
      versions:
        - All
  categories:
    - system
dependencies:
  - franklinkim.nginx
