---

- include: install.yml
  tags:
    - web
    - nginx
    - install
    - nginx-install

- include: config.yml
  tags:
    - web
    - nginx
    - config
    - nginx-config

- include: manage.yml
  when: nginx_sites | length
  tags:
    - web
    - nginx
    - manage
    - nginx-manage

- include: service.yml
  tags:
    - web
    - nginx
    - service
    - nginx-service
